// Builds paper_draft/UICPI_CJSJ_submission.docx (CJSJ Original Research template).
// The manuscript text lives in this file; edit it here and rebuild rather than editing the docx.
//
//   cd paper_draft/cjsj && npm install && node build_cjsj_docx.js [output.docx]
//
// Formatting values (page geometry, Title/Heading1/Heading2 styles, abstract, footnote and
// reference paragraph properties) were taken from the template file's own XML.
// Reads fig2_lead_times_cjsj.png from this directory (generated by fig2_cjsj.py).
// Check the result with verify_cjsj_submission.py. Document properties are left generic on purpose.
const fs = require("fs");
const path = require("path");
const {
  Document, Packer, Paragraph, TextRun, AlignmentType,
  ImageRun, FootnoteReferenceRun, SectionType, LevelFormat,
} = require("docx");

const FONT = "Times New Roman";
const BODY_SIZE = 20;   // 10pt
const ABS_SIZE = 18;    // 9pt (abstract, per template)
const CAP_SIZE = 16;    // 8pt (footnote, references, figure caption, per template)

const PAGE_W = 12240, PAGE_H = 15840; // US Letter, per template sectPr
const MARGIN = 1080;                  // 0.75in, per template pgMar
const COL_SPACE = 288;                // per template <w:col w:space="288">

// ---- body paragraph: justified, firstLine 288, spacing after120/before0, line228 (0.95) ----
function body(runsOrText, opts = {}) {
  const runs = typeof runsOrText === "string" ? [{ text: runsOrText }] : runsOrText;
  return new Paragraph({
    alignment: AlignmentType.JUSTIFIED,
    indent: { firstLine: 288 },
    spacing: { after: 120, before: 0, line: 228, lineRule: "auto" },
    children: runs.map(r => new TextRun({
      text: r.text, font: FONT, size: r.size || BODY_SIZE,
      bold: r.bold, italics: r.italic, superScript: r.sup,
    })),
  });
}

// ---- H1: numbered ("I.", "II."...), centered, smallCaps, NOT bold, single-spaced ----
function h1(numeral, text) {
  return new Paragraph({
    keepNext: true,
    alignment: AlignmentType.CENTER,
    spacing: { before: 240, after: 80, line: 240, lineRule: "auto" },
    children: [
      new TextRun({ text: `${numeral}. ${text}`, font: FONT, size: BODY_SIZE, smallCaps: true }),
    ],
  });
}

// ---- unnumbered version (Acknowledgements / References) — same style, no numeral ----
function h1Unnumbered(text) {
  return new Paragraph({
    keepNext: true,
    alignment: AlignmentType.CENTER,
    spacing: { before: 240, after: 80, line: 240, lineRule: "auto" },
    children: [
      new TextRun({ text, font: FONT, size: BODY_SIZE, smallCaps: true }),
    ],
  });
}

// ---- H2 sub-heading (template's Heading2 style): italic, left, indented, NOT smallCaps ----
function h2(text) {
  return new Paragraph({
    keepNext: true,
    indent: { left: 144 },
    spacing: { before: 120, after: 60, line: 240, lineRule: "auto" },
    children: [
      new TextRun({ text, font: FONT, size: BODY_SIZE, italics: true }),
    ],
  });
}

const imgBuf = fs.readFileSync(path.join(__dirname, "fig2_lead_times_cjsj.png"));
const IMG_W = 315, IMG_H = 236; // 1314x984px @400dpi = 3.285in: placed 1:1 so 8pt figure text stays 8pt

const doc = new Document({
  numbering: {
    config: [{
      reference: "refs",
      levels: [{
        level: 0, format: LevelFormat.DECIMAL, text: "[%1]", alignment: AlignmentType.LEFT,
        style: { paragraph: { indent: { left: 360, hanging: 360 } }, run: { font: FONT, size: CAP_SIZE } },
      }],
    }],
  },
  styles: { default: { document: { run: { font: FONT, size: BODY_SIZE } } } },
  footnotes: {
    1: {
      children: [
        new Paragraph({
          alignment: AlignmentType.JUSTIFIED,
          indent: { firstLine: 202 },
          spacing: { line: 240, lineRule: "auto" },
          children: [new TextRun({ text: "W. C. Er is with Raffles Institution, Singapore (corresponding author, e-mail: wcerbiz@gmail.com).", font: FONT, size: CAP_SIZE })],
        }),
      ],
    },
  },
  sections: [
    {
      // single continuous section, two columns throughout (matches template's single sectPr)
      properties: {
        type: SectionType.NEXT_PAGE,
        page: {
          size: { width: PAGE_W, height: PAGE_H },
          margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN, header: 432, footer: 432 },
        },
        column: { count: 2, space: COL_SPACE },
      },
      children: [
        // Title — bold 16pt centered (matches template's Title style: b, sz=32, jc=center, before=360)
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 360, line: 240, lineRule: "auto" },
          children: [new TextRun({
            text: "UICPI: A Method for Collecting Chain and Independent Restaurant Prices at Scale, with Evidence from the United States",
            font: FONT, size: 32, bold: true,
          })],
        }),
        // Author line — 11pt, centered, NOT bold (matches template: sz=22, jc=center, after=320)
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 320, before: 0, line: 240, lineRule: "auto" },
          children: [
            new TextRun({ text: "Wen Chen Er", font: FONT, size: 22 }),
            new FootnoteReferenceRun(1),
          ],
        }),

        // Abstract — run-in bold-italic lead + bold body, 9pt, justified, firstLine 202, single-spaced
        new Paragraph({
          alignment: AlignmentType.JUSTIFIED,
          indent: { firstLine: 202 },
          spacing: { before: 20, after: 0, line: 240, lineRule: "auto" },
          children: [
            new TextRun({ text: "Abstract", font: FONT, size: ABS_SIZE, bold: true, italics: true }),
            new TextRun({
              text: "—Consumer price indices in developing economies rely on infrequent collection, and algorithmic alternatives like the MIT Billion Prices Project exclude food-service prices entirely. We present a method for collecting restaurant menu prices from Wayback Machine archives and live delivery platforms, and use them to construct a Unified Independent-Chain Price Index (UICPI) across eight countries (48,730 observations, 2018–June 2026). Applied to the United States (n=31), UICPI Granger-leads headline CPI at an exact one-month calendar lag (F(1,28)=4.20, analytic p=0.0499; permutation p=0.052–0.069) — the most numerically interesting result in the panel, not a validated finding, given the narrow margin and an unadjusted ~14% multiple-testing rate across three clean country tests. India (n=47) and Malaysia (n=30), the panel's other genuine tests on real monthly CPI, return clean nulls (p=0.474, p=0.742), arguing against generalizing the US result. The contribution is chiefly methodological: a publicly available, auditable pipeline for chain and independent-vendor food-price collection at scale.",
              font: FONT, size: ABS_SIZE, bold: true,
            }),
          ],
        }),

        h1("I", "Methods"),
        h2("Data Collection"),
        body("We assembled an eight-country panel (United States, United Kingdom, Malaysia, Singapore, India, Indonesia, Australia, Thailand) of restaurant menu prices from two sources: (1) a Wayback Machine historical sweep, querying the Internet Archive's CDX index for archived menu pages on delivery and restaurant-listing platforms (GrabFood, Deliveroo, Menulog, Zomato) and the MenuPages US menu directory, with prices extracted via platform-specific parsers matched to each site's HTML structure (Schema.org JSON-LD, Next.js embedded state, DOM markers, or embedded JSON, depending on platform vintage); and (2) live forward collection via a Playwright-driven nightly scraper. Before any Wayback sweep, a Phase 0 probe of the CDX index checks each candidate (source, country) pair for archive coverage, price-token density, and bot-blocking; pairs that fail (e.g., iFood Brazil, ShopeeFood Indonesia) are logged and excluded rather than swept. The panel totals 48,730 price observations (snapshot of 2026-06-19) spanning 2018 to June 2026, unevenly distributed across countries."),

        h2("Index Construction"),
        body("For each country-month, prices are converted to USD, capped at 300 rows per (country, year_month) to prevent dense months from dominating the aggregate, and combined by taking the median price per restaurant, then the median of restaurant medians. The index level is the geometric mean of category relatives, based at 100 in the first month with adequate coverage. Chain and independent-vendor sub-indices are computed separately and combined into a headline series. Delivery-platform data from DoorDash is collected but excluded from index construction, on the premise that platform-specific pricing (surge, promotions, fees) differs from menu pricing. In a source-stratified contrast under the earlier (pre-respec) AIC-selected VAR specification, pooling DoorDash data (which also lengthens the overlap window) removed the US signal; this has not been re-verified under the calendar-true specification, and the premise is not tested here."),

        h2("Analysis"),
        body([
          { text: "For each country with at least 24 overlapping monthly observations against national CPI, we test whether UICPI Granger-leads CPI, following Cavallo and Rigobon [1]. For the United States we use a calendar-true, fixed one-month-lag specification — CPI_chg(t) ~ CPI_chg(t−1) + UICPI(t−1) — rather than AIC-based lag selection, so the theoretically motivated one-month lag is tested directly; significance is assessed via an analytic F-test and two permutation designs (naive shuffle and circular block, the latter preserving the serial dependence a Granger test on monthly data relies on). India and Malaysia, like the US and UK, have monthly-published CPI (Singapore, Indonesia and Thailand rely on annually-interpolated World Bank CPI, and Australia on quarterly-interpolated CPI), and receive standard Granger tests. The remaining countries are not yet tested because they fall below the 24-month threshold (United Kingdom 18, Australia 23, Indonesia 20, Singapore 8, Thailand 0), a sample-size limit rather than an exclusion by CPI type." },
        ]),

        h1("II", "Results & Discussion"),
        body("The headline result is the United States: over 31 overlapping months (2018-04–2024-10), UICPI Granger-leads CPI at exactly one month (F(1,28)=4.20, analytic p=0.0499; Fig. 1). Both permutation checks land in the same narrow band (shuffle p=0.052; circular block p=0.069, the more appropriate check given monthly serial dependence), so none of the three tests is a clean rejection of independence, and the result should be read as suggestive rather than confirmatory. It strengthens under a causal forward-fill robustness check that uses only past information to fill single-month gaps (F(1,35)=9.05, p=0.0048, n=38). The finding is a timing signal only — UICPI changes precede CPI changes by one month — with no claim made about the magnitude of the eventual CPI movement."),
        body("India (n=47) and Malaysia (n=30), the panel's other two countries with real monthly CPI and sufficient overlap, return clean nulls (F=0.521, p=0.474; F=0.111, p=0.742). The India null is especially informative given its sample size and stationarity: it suggests the menu-to-CPI channel is not universal, plausibly because Indian CPI weighting emphasizes staples subject to monsoon and procurement-policy pricing rather than restaurant repricing, and because the Indian series is restaurant-aggregate (Zomato “cost for two”), not item-level, which may smooth the high-frequency variation the US result depends on."),
        body("Three tests meet every condition this paper requires of a clean test: real monthly CPI, ≥24 overlapping months, reproducible statistics. Under a global null, the chance of observing at least one p≤0.05 among three independent tests is 1−0.95³≈14.3%; no multiplicity correction is applied, the US test was not pre-registered as the primary hypothesis, and 14.3% is the most favourable defensible accounting rather than a conservative one (counting the untested or withdrawn countries would raise it). The US result should therefore be read as the most numerically interesting result in the panel, not as one demonstrated to be distinguishable from chance."),
        body("Two further caveats bound the interpretation. The Vietnam and UAE Wayback slices were found to be systematically mispriced (UAE: digit-fusion in archived price objects; Vietnam: an unconditional \u00f7100 of GrabFood’s priceInMinorUnit, which for VND already carries the raw amount) and were quarantined from the index; no statistic is reported for either country here. And the causal mechanism behind the US lead is ambiguous — labor-cost pass-through and shared exposure to energy-price shocks could each generate the observed sequencing without restaurant repricing being the causal driver of CPI, and the present design cannot separate these from a genuine food-price channel."),
        body("The panel's chief contribution is methodological — a reproducible, publicly available pipeline for chain and independent-vendor food-price collection — rather than the US result itself, which is a proof of concept awaiting replication as the United Kingdom — the only country on real monthly CPI still below the 24-month threshold — crosses it."),

        // Figure — caption below, 8pt, "Figure 1." per template's example caption, not bold
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 120, after: 40, line: 240, lineRule: "auto" },
          children: [new ImageRun({ type: "png", data: imgBuf, transformation: { width: IMG_W, height: IMG_H } })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 160, line: 240, lineRule: "auto" },
          children: [new TextRun({
            text: "Figure 1. Granger causality by country — UICPI leading official CPI (calendar-true specification for the United States). The US bar is hatched: the analytic p-value clears 0.05 but neither permutation check does.",
            font: FONT, size: CAP_SIZE,
          })],
        }),

        h1Unnumbered("Acknowledgements"),
        body("The UICPI codebase and pipeline are publicly available at github.com/thefrogfacedfoot/Inflation-menu for independent audit and reproduction. This work relies on the Internet Archive's Wayback Machine, the UK Office for National Statistics, Malaysia DOSM, and OECD CPI data, and the schema.org Menu specification. The author thanks R. Verbrugge (Federal Reserve Bank of Cleveland) for correspondence on the treatment of food-away-from-home in core-inflation measures."),
        body("Claude and Claude Code (Anthropic) were used extensively throughout this project: for writing and debugging the data-collection and analysis pipeline (scrapers, parsers, the index-construction and Granger-testing code), for exploratory data analysis, and for drafting, condensing, and editing this manuscript, including this Methods and Results/Discussion text. All analytic decisions, experimental design choices, interpretation of results, and conclusions are the author's own; AI assistance was a writing and coding aid, not an independent contributor to the research design or findings."),

        h1Unnumbered("References"),
        new Paragraph({
          numbering: { reference: "refs", level: 0 },
          spacing: { line: 240, lineRule: "auto" },
          children: [new TextRun({
            text: "A. Cavallo and R. Rigobon, “The Billion Prices Project: Using Online Prices for Measurement and Research,” J. Econ. Perspect., vol. 30, no. 2, pp. 151–178, 2016.",
            font: FONT, size: CAP_SIZE,
          })],
        }),
      ],
    },
  ],
});

Packer.toBuffer(doc).then((buf) => {
  const out = process.argv[2] || path.join(__dirname, "..", "UICPI_CJSJ_submission.docx");
  fs.writeFileSync(out, buf);
  console.log("written", out);
});
