#!/usr/bin/env python3
"""Calibrated Ljung-Box(12): does it fix the miscalibration of the raw statistic? SIMULATED data only.

Raw LB(12) on residuals of a regression with 11 month dummies is mechanically
biased: within-month-class residuals sum to zero, forcing NEGATIVE lag-12
autocorrelation (about -0.5 at T=34, -0.15 at T=97), so the chi-square test
rejects far more than 5% under a correct model. The calibrated version compares
the observed LB statistic (y-equation residuals of the unrestricted fit) with its
distribution under the restricted model, regenerated by the registered recursive
block bootstrap, which carries the same dummy-induced bias.

Reports, per DGP and n: raw chi-square LB rejection share, calibrated rejection
share (both at 5%), on the y equation. (The x equation is not bootstrapped: x is
a fixed regressor in the registered scheme.)

Usage: python3 diagnostics/lb_calibrated_check.py --reps 500 --B 199 [--out FILE]
"""
import argparse
import math
import os
import sys
import warnings
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
import numpy as np  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import prereg_analysis as pa  # noqa: E402
import prereg_size_check as sc  # noqa: E402

warnings.filterwarnings("ignore")


def lb_stat(e, lags=12):
    """Ljung-Box Q for residual vector(s); e shape (T,) or (B, T)."""
    e = np.atleast_2d(e)
    T = e.shape[1]
    den = (e ** 2).sum(1)
    q = np.zeros(e.shape[0])
    for k in range(1, lags + 1):
        rho = (e[:, k:] * e[:, :-k]).sum(1) / den
        q += rho ** 2 / (T - k)
    return T * (T + 2) * q


def regenerate(fit, idx, n_dum):
    """Recursive restricted-model draws of y* (B, T), same scheme as prereg_analysis.null_F_recursive."""
    p, T = fit.p, fit.T
    beta_r, *_ = np.linalg.lstsq(fit.Zr, fit.Y, rcond=None)
    base = fit.Zr[:, :1 + n_dum] @ beta_r[:1 + n_dum]
    phi = beta_r[1 + n_dum:]
    B = idx.shape[0]
    ystar = np.zeros((B, T + p))
    first = fit.Zr[0, 1 + n_dum: 1 + n_dum + p]
    for j in range(p):
        ystar[:, p - 1 - j] = first[j]
    E = fit.e_r[idx]
    for t in range(T):
        ystar[:, p + t] = base[t] + sum(phi[j] * ystar[:, p + t - 1 - j] for j in range(p)) + E[:, t]
    return ystar


def one(args):
    n, seed, dgp, B = args
    rng = np.random.default_rng(seed)
    li, lc = sc.gen_country(rng, n, dgp=dgp)
    pr = pa.prepare("S", li, lc)
    p = pa.select_lag(pr.y, pr.x, pr.moy)["p"]
    f = pa.granger_fit(pr.y, pr.x, pr.moy, p)
    raw_rej = f.lb_p_y < 0.05
    e_u = f.Mu @ f.Y
    q_obs = lb_stat(e_u)[0]
    b = pa.block_length(f.T)
    starts = rng.integers(0, f.T, size=(B, math.ceil(f.T / b)))
    idx = pa.circular_blocks(starts, b, f.T, f.T)
    ys = regenerate(f, idx, 11)
    k_common = 12
    xl = f.Zu[:, k_common + p:]
    qs = np.empty(B)
    for i in range(B):
        yl = np.column_stack([ys[i, p - 1 - j: p - 1 - j + f.T] for j in range(p)])
        Zu = np.column_stack([f.Zu[:, :k_common], yl, xl])
        Y = ys[i, p:]
        r = Y - Zu @ np.linalg.lstsq(Zu, Y, rcond=None)[0]
        qs[i] = lb_stat(r)[0]
    p_cal = (1 + np.sum(qs >= q_obs)) / (B + 1)
    return raw_rej, p_cal < 0.05


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reps", type=int, default=500)
    ap.add_argument("--B", type=int, default=199)
    ap.add_argument("--seed", type=int, default=20261008)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    lines = [f"Calibrated vs raw Ljung-Box(12), y equation, 5% level, simulated null series; reps={a.reps} B={a.B} seed={a.seed}", "",
             f"{'DGP':<15}{'n':>5}{'raw chi-sq':>13}{'calibrated':>12}"]
    with ProcessPoolExecutor() as ex:
        for dgp in sc.DGPS:
            for n in (36, 100):
                res = list(ex.map(one, [(n, a.seed + 1000 * n + i, dgp, a.B) for i in range(a.reps)], chunksize=5))
                lines.append(f"{dgp:<15}{n:>5}{np.mean([r[0] for r in res]):>13.4f}{np.mean([r[1] for r in res]):>12.4f}")
                print(lines[-1], flush=True)
    if a.out:
        Path(a.out).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
